version: "3"
services:
  reverse-proxy:
    build:
      context: ./udagram-reverseproxy
    image: reverse-proxy
  udagram-backend-user:
    build:
      context: ./udagram-backend-user
    image: udagram-backend-user
  udagram-backend-feed:
    build:
      context: ./udagram-backend-feed
    image: udagram-backend-feed
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend
